CREATE TABLE DIRECTORES
	(DNI varchar (8) PRIMARY KEY,
     NomApels nvarchar (255),
     numero int,
     DNIJefe varchar (8) NOT NULL,
     FOREIGN KEY (DNIJefe) REFERENCES DIRECTORES(DNI) ON DELETE CASCADE ON UPDATE CASCADE,
     FOREIGN KEY (numero) REFERENCES DESPACHO(numero) ON DELETE CASCADE ON UPDATE CASCADE
    );
