USE CIENTIFICOS;
CREATE TABLE ASIGNADO_A
	(
    DNI varchar (8) NOT NULL,
    idProyectos char (4) NOT NULL,
    FOREIGN KEY(DNI) REFERENCES CIENTIFICOS(DNI) ON UPDATE CASCADE ON DELETE CASCADE,
    FOREIGN KEY(idProyectos) REFERENCES PROYECTOS(idProyectos) ON UPDATE CASCADE ON DELETE CASCADE
    );
