CREATE TABLE VENTA
	(
    codigoMaquina int NOT NULL,
    codigoCajero int NOT NULL,
    codigo int NOT NULL,
    FOREIGN KEY(codigoMaquina) REFERENCES MAQUINAS_REGISTRADORAS(codigoMaquina) ON DELETE CASCADE ON UPDATE  CASCADE,
    FOREIGN KEY(codigoCajero) REFERENCES CAJEROS(codigoCajero) ON DELETE CASCADE ON UPDATE  CASCADE,
    FOREIGN KEY(codigo) REFERENCES PRODUCTOS(codigo) ON DELETE CASCADE ON UPDATE  CASCADE
    );
